---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helm-provisioner-admin
rules:
- nonResourceURLs:
  - /bundles/*
  verbs:
  - get
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  verbs:
  - create
- apiGroups:
  - core.rukpak.io
  resources:
  - bundledeployments
  verbs:
  - list
  - update
  - watch
- apiGroups:
  - core.rukpak.io
  resources:
  - bundledeployments/finalizers
  verbs:
  - update
- apiGroups:
  - core.rukpak.io
  resources:
  - bundledeployments/status
  verbs:
  - patch
  - update
