---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: core-admin
rules:
- apiGroups:
  - core.rukpak.io
  resources:
  - bundles
  verbs:
  - list
  - watch
