name: e2e

on:
  pull_request:
  push:

jobs:
  e2e-kind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v2
      with:
        go-version: '~1.17'

    - name: Install kind binary
      env:
        KIND_VERSION: v0.12.0
        KIND_OS: kind-linux-amd64
      run: |
        curl -sLo kind "https://github.com/kubernetes-sigs/kind/releases/download/${KIND_VERSION}/${KIND_OS}"
        chmod +x kind
        sudo mv kind /bin/

    - name: Run e2e tests
      run: make e2e KIND=/bin/kind TEST=git
