name: sanity

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - main

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '~1.17'
      - name: Run verification checks
        run: make verify
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '~1.17'
      - id: golangci-lint
        run: echo "::set-output name=version::$(cd hack/tools; go list -m github.com/golangci/golangci-lint | cut -d' ' -f2)"
      - name: Run linting checks
        uses: golangci/golangci-lint-action@v2
        with:
          version: ${{ steps.golangci-lint.outputs.version }}
  go-apidiff:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '~1.17'
      - id: go-apidiff
        run: echo "::set-output name=version::$(cd hack/tools; go list -m github.com/joelanford/go-apidiff | cut -d' ' -f2)"
      - name: Run go-apidiff
        uses: joelanford/go-apidiff@main
        with:
          version: ${{ steps.go-apidiff.outputs.version }}
